language:
  java

jdk:
  openjdk11

dist:
  xenial

services:
  postgresql

addons:
  postgresql: '13'
  apt:
    packages:
      - postgresql-13
      - postgresql-client-13

before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-13 postgresql-client-13
  - sudo cp /etc/postgresql/{9.6,13}/main/pg_hba.conf
  - sudo service postgresql restart 13

script:
  - mvn clean install

before_script:
  - psql -c 'create database twittertest;' -U postgres
  - psql -c 'create database twitter;' -U postgres

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - PGUSER=postgres
    - PGPORT=5432
    - CODECOV_TOKEN="a57f9ff0-a15a-453a-b76c-750140eabd87"
  jobs:
    - DB_PORT=5432 DB_USERNAME=postgres
